name: Deploy image
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build, Tag, and Push Docker Image
        run: |
          docker build -t test:0.1 .  
          docker tag test:0.1 sindhujadevops/test:0.1
          docker push sindhujadevops/test:0.1

      - name: Run Docker Container
        run: |
          docker run -d --name my_container -p 8080:8080 sindhujadevops/test:0.1

      - name: Stop and Remove Container
        run: |
          docker stop my_container
          docker rm my_container

      - name: Logout from Docker Hub
        run: docker logout
