name: Deploy image
on:
 workflow_dispatch:
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: login to dockerhub
      uses: docker/login-action@v2
      with:
        username: "sindhujadevops"
        password: "saahas12@U"
    - name: push docker image
      run: |
        docker build -t test:0.1 .  
        docker tag test:0.1 sindhujadevops/test:0.1
        docker push sindhujadevops/test:0.1
        docker run -p 8080:8080 sindhujadevops/test:0.1
        docker stop sindhujadevops/test:0.1 stop sindhujadevops
        docker logout
    
